<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
        <link rel="stylesheet" href="../assets/css/style.css">
        <style>
            body{
                background-color: whitesmoke;
            }
        </style>
</head>

<body class="d-flex justify-content-center align-items-center vh-100">
    <div class="container text-center">
        <?php foreach ($res as $val) { ?>
            <div class="overflow-hidden mb-3">
                <div class="row gy-5 justify-content-center">
                    <div class="col-6">
                        <div class="p-3 bg-light border"><?= $val['nom'] ?></div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</body>

</html>
